### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by Gelbpunkt** [feminists/girlswithout.top#3]
We need to replace the favicon.ico and logo.png with our own.

**Comment by maxx0911** [comment]
any suggestions on what the logo should be?
else I'll whip up a gradient square

**Comment by Gelbpunkt** [comment]
@maxx0911 it should fit the title of the website

**Comment by maxx0911** [comment]
thoughts on this? I took the symbol for female and removed the top

![notop](https://user-images.githubusercontent.com/47576240/94858301-22e1d200-0433-11eb-8ede-4c50e8ad5d31.png)

**Comment by Gelbpunkt** [comment]
Looks good
